# defaults file for distribution

# The version of distribution to install
distribution_version: 2.16.2

# whether to enable HA
distribution_ha_enabled: false

distribution_ha_node_type: master

# The location where distribution should install
jfrog_home_directory: /opt/jfrog

# The remote distribution download file
distribution_tar_file_name: jfrog-distribution-{{ distribution_version }}-linux.tar.gz
distribution_tar: https://releases.jfrog.io/artifactory/jfrog-distribution/distribution-linux/{{ distribution_version }}/{{ distribution_tar_file_name }}

# Timeout in seconds for URL request
distribution_download_timeout: 10

# The distribution install directory
distribution_untar_home: "{{ jfrog_home_directory }}/jfrog-distribution-{{ distribution_version }}-linux"
distribution_home: "{{ jfrog_home_directory }}/distribution"

distribution_install_script_path: "{{ distribution_home }}/app/bin"
distribution_thirdparty_path: "{{ distribution_home }}/app/third-party"
distribution_archive_service_cmd: "{{ distribution_install_script_path }}/installService.sh"
distribution_service_file: /lib/systemd/system/distribution.service

# distribution users and groups
distribution_user: distribution
distribution_group: distribution

distribution_uid: 1040
distribution_gid: 1040

distribution_daemon: distribution

# Redis details
distribution_redis_url: "redis://localhost:6379"
distribution_redis_password: password

# if this is an upgrade
distribution_upgrade_only: false

distribution_system_yaml_template: system.yaml.j2

# Provide systemyaml content below with 2-space indentation
distribution_systemyaml: |-
  configVersion: 1
  shared:
    jfrogUrl: {{ jfrog_url }}
    node:
      ip: {{ ansible_host }}
      id: {{ ansible_hostname }}
    database:
      type: "{{ distribution_db_type }}"
      driver: "{{ distribution_db_driver }}"
      url: "{{ distribution_db_url }}"
      username: "{{ distribution_db_user }}"
      password: "{{ distribution_db_password }}"
    redis:
      connectionString: "{{ distribution_redis_url }}"
      password: "{{ distribution_redis_password }}"
    security:
      joinKey: {{ join_key }}
  router:
    entrypoints:
      internalPort: 8046

# Note: distribution_systemyaml_override is by default false,  if you want to change default distribution_systemyaml
distribution_systemyaml_override: false
