galaxy_info:
  author: "Jeff Fry <jefff@jfrog.com>"
  description: "The postgres role will install Postgresql software and configure a database and user to support an Artifactory or Xray server."
  company: JFrog

  issue_tracker_url: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"

  license: license (GPL-2.0-or-later)

  min_ansible_version: 2.9

  galaxy_tags:
    - postgres
    - jfrog

dependencies: []