- name: Play for postgres_servers
  hosts: postgres_servers
  collections:
    - community.postgresql
    - community.general
  roles:
    - role: postgres
      when: postgres_enabled | bool

- name: Play for artifactory_servers
  hosts: artifactory_servers
  collections:
    - community.general
  serial:
    - 1
    - 100%
  roles:
    - role: artifactory
      when: artifactory_enabled | bool

- name: Play for xray_servers
  hosts: xray_servers
  collections:
    - community.general
  roles:
    - role: xray
      when: xray_enabled | bool

- name: Play for distribution_servers
  hosts: distribution_servers
  collections:
    - community.general
  roles:
    - role: distribution
      when: distribution_enabled | bool

- name: Play for insight_servers
  hosts: insight_servers
  collections:
    - community.general
    - ansible.posix
  roles:
    - role: insight
      when: insight_enabled | bool
