---
- name: define distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

#- name: define postgres version-specific variables
#  include_vars: "{{ lookup('first_found', params) }}"
#  vars:
#    params:
#      files:
#        - "{{ ansible_os_family }}_pg-{{ postgres_server_version }}.yml"
#        - "{{ ansible_os_family }}_pg-default.yml"
#      paths:
#        - "vars"
#      skip: true
#  ignore_errors: true

- name: create directory for bind mount if necessary
  file:
    path: "{{ postgres_server_bind_mount_var_lib_pgsql_target }}"
    state: directory
  become: true
  when: postgres_server_bind_mount_var_lib_pgsql


- name: perform bind mount if necessary
  mount:
    path: "/var/lib/pgsql"
    src: "{{ postgres_server_bind_mount_var_lib_pgsql_target }}"
    opts: bind
    state: mounted
    fstype: none
  become: true
  when: postgres_server_bind_mount_var_lib_pgsql

- name: perform installation
  include_tasks: "{{ ansible_os_family }}.yml"

- name: extend path
  copy:
    dest: /etc/profile.d/postgres-path.sh
    mode: a=rx
    content: "export PATH=$PATH:/usr/pgsql-{{ postgres_server_version }}/bin"
  become: true

- name: initialize PostgreSQL database cluster
  environment:
    LC_ALL: "en_US.UTF-8"
  vars:
    ansible_become: "{{ postgres_server_initdb_become }}"
    ansible_become_user: "{{ postgres_server_user }}"
  command: "{{ postgres_server_cmd_initdb }} {{ postgres_server_data_location }}"
  args:
    creates: "{{ postgres_server_data_location }}/PG_VERSION"

- name: install postgres configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgres_server_config_location }}/{{ item }}"
    owner: postgres
    group: postgres
    mode: u=rw,go=r
  vars:
    ansible_become: "{{ postgres_server_initdb_become }}"
    ansible_become_user: "{{ postgres_server_user }}"
  loop:
    - pg_hba.conf
    - postgresql.conf

- name: enable postgres service
  systemd:
    name: "{{ postgres_server_service_name }}"
    state: started
    enabled: yes
  become: true

- name: Create artifactory users
  become_user: postgres
  become: true
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    conn_limit: "-1"
  no_log: true  # secret passwords

- name: Create a artifactory database
  become_user: postgres
  become: true
  postgresql_db:
    name: artifactory
    owner: "{{ db_user }}"
    encoding: UTF-8

- name: Grant privs to artifactory on artifactory db
  become_user: postgres
  become: true
  postgresql_privs:
    database: artifactory
    role: artifactory
    state: present
    privs: ALL
    type: database

- name: restart postgres
  service:
    name: "{{ postgres_server_service_name }}"
    state: restarted
  become: true