distribution_installer_scenario:
  main:
    - {
        "expecting": "(data|installation) directory \\(",
        "sending": "{{ distribution_home }}"
      }
    - {
      "expecting": "join key.*:",
      "sending": "{{ join_key }}"
      }
    - {
        "expecting": "jfrog url:",
        "sending": "{{ jfrog_url }}"
      }
    - {
        "expecting": "do you want to continue",
        "sending": "y"
      }
    - {
        "expecting": "please specify the ip address of this machine",
        "sending": "{{ ansible_host }}"
      }
    - {
        "expecting": "are you adding an additional node",
        "sending": "{% if distribution_ha_node_type is defined and distribution_ha_node_type == 'master' %}n{% else %}y{% endif %}"
      }
    - {
        "expecting": "do you want to install postgresql",
        "sending": "n"
      }
    - {
        "expecting": "postgresql url.*example",
        "sending": "{{ distribution_db_url }}"
      }
    - {
        "expecting": "(postgresql|database)?\\s?username.*",
        "sending": "{{ distribution_db_user }}"
      }
    - {
        "expecting": "(confirm\\s?)?(postgresql|database)?\\s?password.*:",
        "sending": "{{ distribution_db_password }}"
      }
