galaxy_info:
  author: "JFrog Maintainers Team <installers@jfrog.com>"
  description: "The artifactory role installs the Artifactory Pro software onto the host. Per the Vars below, it will configure a node as primary or secondary. This role uses secondary roles artifactory_nginx to install nginx."
  company: JFrog

  issue_tracker_url: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"

  license: license (Apache-2.0)

  min_ansible_version: 2.9

  galaxy_tags:
    - artifactory
    - jfrog

dependencies: []