apiVersion: v2
appVersion: 7.41.7
dependencies:
  - name: artifactory-ha
    version: 107.41.7
    repository: https://charts.jfrog.io/
description: Openshift JFrog Artifactory HA subcharting Artifactory HA to work in Openshift environment
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/artifactory-ha/logo/artifactory-logo.png
keywords:
- artifactory
- jfrog
- devops
maintainers:
- email: vinaya@jfrog.com
  name: Vinay Aggarwal
- email: johnp@jfrog.com
  name: John Peterson
name: openshift-artifactory-ha
sources:
- https://bintray.com/jfrog/product/JFrog-Artifactory-Pro/view
- https://github.com/jfrog/charts
version: 107.41.7
