- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    name: ["net-tools", "locales"]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure UTF-8 locale exists
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
