---
dependencies: []

galaxy_info:
  author: "JFrog Maintainers Team <installers@jfrog.com>"
  description: "The insight role will install insight software onto the host. An Artifactory server and Postgress database are required."
  company: JFrog
  issue_tracker_url: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"
  license: 'license (Apache-2.0)'
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - insight
    - jfrog
