xray_installer_scenario:
  main:
    - {
        "expecting": "(data|installation) directory \\(",
        "sending": "{{ xray_home }}"
      }
    - {
        "expecting": "jfrog url( \\(.+\\))?:(?!.*Skipping prompt)",
        "sending": "{{ jfrog_url }}"
      }
    - {
        "expecting": "join key:(?!.*Skipping prompt)",
        "sending": "{{ join_key }}"
      }
    - {
        "expecting": "please specify the ip address of this machine(?!.*Skipping prompt)",
        "sending": "{{ ansible_host }}"
      }
    - {
        "expecting": "are you adding an additional node",
        "sending": "{% if xray_ha_node_type is defined and xray_ha_node_type == 'master' %}n{% else %}y{% endif %}"
      }
    - {
        "expecting": "do you want to install postgresql",
        "sending": "n"
      }
    - {
        "expecting": "(postgresql|database) url",
        "sending": "{{ xray_db_url }}"
      }
    - {
        "expecting": "(postgresql|database) password",
        "sending": "{{ xray_db_password }}"
      }
    - {
        "expecting": "(postgresql|database) username",
        "sending": "{{ xray_db_user }}"
      }
    - {
        "expecting": "confirm database password",
        "sending": "{{ xray_db_password }}"
      }
    - {
        "expecting": "rabbitmq active node name:",
        "sending": "{{ ansible_machine_id }}"
      }
    - {
        "expecting": "rabbitmq active node ip:",
        "sending": "{{ ansible_host }}"
      }
