# platform collection version
platform_collection_version: 10.18.2

# indicates were this collection was downlaoded from (galaxy, automation_hub, standalone)
ansible_marketplace: galaxy

ansible_python_interpreter: "/usr/bin/python3"
