apiVersion: v1
appVersion: 3.14.3
description: Universal component scan for security and license inventory and impact
  analysis
home: https://www.jfrog.com/xray/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/xray/logo/xray-logo.png
keywords:
- xray
- jfrog
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: xray
sources:
- https://bintray.com/jfrog/product/xray/view
- https://github.com/jfrog/charts
version: 6.8.3
