---
all:
    vars:
        ansible_user: "ubuntu"
        ansible_ssh_private_key_file: "/Users/jefff/.ssh/ansible-priv.pem"
        ansible_ssh_common_args: '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -A ubuntu@13.82.225.20 -W %h:%p"'
    children:
        database:
            hosts:
                34.239.107.0:
                    dbs:
                        - { db_name: "artifactory", db_owner: "artifactory" }
                        - { db_name: "xraydb", db_owner: "xray" }
                    db_users:
                        - { db_user: "artifactory", db_password: "Art1fAct0ry" }
                        - { db_user: "xray", db_password: "xray" }
        artifactory:
            hosts:
                54.237.207.135:
                    artifactory_license1: x
                    artifactory_license2: x
                    artifactory_license3: x
                    artifactory_license4: x
                    artifactory_license5: x
                    db_download_url: "https://jdbc.postgresql.org/download/postgresql-42.2.12.jar"
                    db_type: "postgresql"
                    db_driver: "org.postgresql.Driver"
                    db_url: "jdbc:postgresql://10.0.0.59:5432/artifactory"
                    db_user: "artifactory"
                    db_password: "Art1fAct0ry"
                    server_name: "ec2-54-237-207-135.compute-1.amazonaws.com"
        xray:
            hosts:
                100.25.104.174:
                    jfrog_url: "http://ec2-54-237-207-135.compute-1.amazonaws.com"
                    db_type: "postgresql"
                    db_driver: "org.postgresql.Driver"
                    db_url: "postgres://10.0.0.59:5432/xraydb?sslmode=disable"
                    db_user: "xray"
                    db_password: "xray"
