---
all:
    vars:
        ansible_user: "ubuntu"
        ansible_ssh_private_key_file: "/Users/jefff/.ssh/ansible-priv.pem"
    children:
        database:
            hosts:
                #artifactory database
                52.86.32.79:
                    db_users:
                        - { db_user: "artifactory", db_password: "Art1fAct0ry" }
                    dbs:
                        - { db_name: "artifactory", db_owner: "artifactory" }
        artifactory:
            vars:
                artifactory_version: 7.4.1
                artifactory_ha_enabled: true
                master_key: "c97b862469de0d94fbb7d48130637a5a"
                join_key: "9bcca98f375c0728d907cc6ee39d4f02"
                db_download_url: "https://jdbc.postgresql.org/download/postgresql-42.2.12.jar"
                db_type: "postgresql"
                db_driver: "org.postgresql.Driver"
                db_url: "jdbc:postgresql://10.0.0.160:5432/artifactory"
                db_user: "artifactory"
                db_password: "Art1fAct0ry"
                server_name: "ec2-100-25-104-198.compute-1.amazonaws.com"
                certificate: |
                    -----BEGIN CERTIFICATE-----
                    x
                    -----END CERTIFICATE-----
                certificate_key: |
                    -----BEGIN PRIVATE KEY-----
                    x
                    -----END PRIVATE KEY-----
            children:
                primary:
                    hosts:
                        100.25.104.198:
                            artifactory_is_primary: true
                            artifactory_license1: x
                            artifactory_license2: x
                            artifactory_license3: x
                            artifactory_license4: x
                            artifactory_license5: x
                secondary:
                    hosts:
                        54.160.107.157:
                        35.153.79.44:
                    vars:
                        artifactory_is_primary: false

